### ISSUE TITLE
glance not installed?

### ISSUE THREAD

**Issue by johnstudarus** [OpenStackSanDiego/osa-workshop#13]
PLAY [Install glance services] ***********************************************************************************
skipping: no hosts matched

**Comment by ccollicutt** [comment]
Hmm it is in my deployment and I can upload an image.

```
root@infra0-utility-container-5d075e9a:~# os image list
+--------------------------------------+--------+--------+
| ID                                   | Name   | Status |
+--------------------------------------+--------+--------+
| 0f5755a8-0b69-485d-b0f0-44754f38fe12 | xenial | active |
+--------------------------------------+--------+--------+
```

**Comment by johnstudarus** [comment]
Probably a false alarm... Just saw that message fly by and wanted to take a
closer look...

**Comment by johnstudarus** [comment]
Glace is working OK. I was able to upload an image OK.
