### ISSUE TITLE
ip address not being assigned to br-vxlan in setup-bridges.sh script

### ISSUE THREAD

**Issue by ccollicutt** [OpenStackSanDiego/osa-workshop#21]
Right now it's being assigned to br-mgmt. Did we want both IPs being set on br-mgmt, or one on br-mgmt and one on br-vxlan?

https://github.com/OpenStackSanDiego/osa-workshop/blob/b196ace453b94f531cd109d7ea7aa58b23040353/terraform/setup-bridges.tpl#L26

**Comment by johnstudarus** [comment]
Ugh! Typo - that VXLAN_IP should be on br-vxlan. Good catch.
