### ISSUE TITLE
template error while templating string

### ISSUE THREAD

**Issue by johnstudarus** [OpenStackSanDiego/osa-workshop#29]
This error pops up time to time when running the OSA playbooks.

fatal: [infra0_keystone_container-3286fdbc]: FAILED! => {"msg": "The conditional check 'physical_host in hostvars['localhost']['unbound_physical_hosts']' failed. The error was: template error while templating string: unexpected '|'. The error appears to have been in '/opt/openstack-ansible/playbooks/common-tasks/unbound-clients.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n#on the same physical_host\n- name: Apply resolver sorting\n  ^ here

**Comment by johnstudarus** [comment]
Here's the file it doesn't like:

https://github.com/openstack/openstack-ansible/blob/master/playbooks/common-tasks/unbound-clients.yml#L18

**Comment by medberry** [comment]
those tasks get included 35 different times and the file hasn't changed recently. Maybe one of the 35 including files has changed errantly.
(I see no issue with the yaml.)

**Comment by johnstudarus** [comment]
It's bizarre. It's intermittent...

Does it depend on any infrastructure? IP addresses? Resolver IPs?

**Comment by ccollicutt** [comment]
I did see someone talking about a similar issue:

http://eavesdrop.openstack.org/irclogs/%23openstack-ansible/%23openstack-ansible.2018-10-08.log.html

**Comment by johnstudarus** [comment]
This error never came back so I'm closing.
